import './css/tabler.min.css';
// import './css/tabler-flags.min.css';
// import './css/tabler-payments.min.css';
import './css/tabler-vendors.min.css';
import './css/demo.min.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
      </head>
      <body className="d-flex flex-column" data-bs-theme='dark'>{children}</body>
    </html>
  )
}
