import './css/tabler.min.css';
// import './css/tabler-flags.min.css';
// import './css/tabler-payments.min.css';
import './css/tabler-vendors.min.css';
import './css/demo.min.css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="d-flex flex-column" data-bs-theme='dark'>{children}</body>
    </html>
  )
}
